# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('ind', models.IntegerField(default=4500)),
                ('gr', models.IntegerField(default=0)),
                ('clessons', models.IntegerField(default=8)),
            ],
        ),
    ]
