# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 02:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mystudents', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myteachers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startmoney', models.IntegerField(verbose_name='Баланс на начало месяца')),
                ('nowtmoney', models.IntegerField(verbose_name='Текущий баланс')),
                ('discount', models.IntegerField(verbose_name='Разовая скидка')),
                ('k1', models.IntegerField(verbose_name='Коэф1')),
                ('k2', models.IntegerField(verbose_name='Коэф2')),
                ('k3', models.IntegerField(verbose_name='Коэф3')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mymoney', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
